spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tmall
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Dmgy1Chlr0sql
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.baiyu.tmall.pojo
  configuration:
    map-underscore-to-camel-case: true
